---
- hosts: 172.16.1.120
  tasks:
  - get_url:
     url: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
     dest: /root/
  - yum:
     name: "/root/mysql57-community-release-el7-9.noarch.rpm"
     state: present
  - yum:
     name: mysql-community-server
     state: present
  - service: 
     name: mysqld
     state: started
     enabled: true
  - shell: cat /var/log/mysqld.log | grep 'A temporary password'
#  - name: test mysql_secure_installation
#    mysql_secure_installation:
#     login_password: ''
#     new_password: Admin@1212
#     user: root
#     login_host: localhost
#     hosts: ['localhost', '127.0.0.1', '::1']
#     change_root_password: true
#     remove_anonymous_user: true
 #    disallow_root_login_remotely: true
#     remove_test_db: true
#    register: mysql_secure

# To see detailed output
#  - debug:
#      var: mysql_secure 
     
